/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;

import br.com.ifba.curso.service.CursoIService;
import br.com.ifba.curso.entity.Curso;
import jakarta.annotation.PostConstruct;
import javax.swing.JOptionPane;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
/**
 *
 * @author misae
 */

//e aqui é a Classe que representa a tela para listar cursos
@Component
public class CursoListar extends javax.swing.JFrame {
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    
    
    //aqui o objeto sorter para organizar as linhas da tabela conforme o filtro de pesquisa
    private TableRowSorter<DefaultTableModel> sorter;
    
    // agora a tela recebe o Service por injeção via construtor
    @Autowired   
    private CursoIService service;
    

   
    
    private List<Curso> listaCursos;// lista que armazena os cursos recuperados do banco para mostrar na tabela

    //construtor
    public CursoListar() {
        initComponents();
        this.setLocationRelativeTo(null); // centraliza
    }

    
    @PostConstruct
    public void init(){    
    

        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // escondendo a coluna ID
        jTable1.getColumnModel().getColumn(2).setMinWidth(0);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(2).setWidth(0);

        // Carrega os cursos
        //carregarCursos();

        // configura sorter para a tabela 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);

        // document listener para filtrar enquanto digita
        txtProcurar.getDocument().addDocumentListener(new DocumentListener() {

            private void filtrar() {
                String texto = txtProcurar.getText();
                if (texto == null || texto.trim().isEmpty()) {
                    sorter.setRowFilter(null);
                    return;
                }

                // escapando caracteres especiais para evitar PatternSyntaxException
                String safe = Pattern.quote(texto);

                // Tratamentos de exceções na prática
                try {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)^" + safe, 0));
                } catch (PatternSyntaxException ex) {
                    sorter.setRowFilter(null);
                }
            }

            @Override public void insertUpdate(DocumentEvent e) { filtrar(); }
            @Override public void removeUpdate(DocumentEvent e) { filtrar(); }
            @Override public void changedUpdate(DocumentEvent e) { filtrar(); }
        });
    }
    
    public void carregarCursos() {
        
     try {
  
        listaCursos = service.findAll();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        if (listaCursos != null) {
            for (Curso c : listaCursos) {
                model.addRow(new Object[]{
                    c.getNome(),
                    c.getCodigo(),
                    c.getId()
                });
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Erro ao carregar cursos: " + e.getMessage(),
            "Erro",
            JOptionPane.ERROR_MESSAGE);
    }
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtProcurar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProcurar.setBackground(new java.awt.Color(255, 255, 255));
        txtProcurar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProcurar.setForeground(new java.awt.Color(80, 80, 80));
        txtProcurar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProcurar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));
        txtProcurar.setOpaque(true);
        txtProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(txtProcurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Codigo", "ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 510, 375));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 70, 50));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 30));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 30));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 30));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcurarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtProcurarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
    int linhaSelecionada = jTable1.getSelectedRow();

    if (linhaSelecionada == -1) {
    JOptionPane.showMessageDialog(this,
        "Selecione um curso para excluir!",
        "Aviso",
        JOptionPane.WARNING_MESSAGE);
    return;
    }

    // Agora usamos o ID oculto da tabela
    Long id = Long.valueOf(jTable1.getValueAt(linhaSelecionada, 2).toString());

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Excluir este curso?",
        "Confirmar",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {

    // buscar o curso pelo ID via service agora
    Curso curso = service.findById(id);

    // excluir usando o método que já existe no service
    service.delete(curso);
    
    carregarCursos();

    JOptionPane.showMessageDialog(this, "Curso excluído!");
}

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
     // cria uma nova janela JFrame para a tela de adicionar
   
     
    
    ///vai exibir a nova tabela
     CursoAdicionar tela = new CursoAdicionar(this, service);
    tela.setLocationRelativeTo(null);
    tela.setVisible(true);
    

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      
    // pega a linha selecionada
    int linhaSelecionada = jTable1.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this,
            "Selecione um curso para editar!",
            "Aviso",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // pega o ID da coluna oculta
    Long idCurso = Long.valueOf(jTable1.getValueAt(linhaSelecionada, 2).toString());

    // busca o curso pelo ID
    Curso curso = service.findById(idCurso);

    if (curso == null) {
        JOptionPane.showMessageDialog(this,
            "Curso não encontrado!",
            "Erro",
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 👉 AQUI VOCÊ COLOCA
    CursoEditar tela = new CursoEditar(
        this,               // passa a tela principal
        service,            // passa o service
        curso.getId(),      // passa o ID
        curso.getNome(),    // nome atual
        curso.getCodigo()   // código atual
    );

    tela.setLocationRelativeTo(null);
    tela.setVisible(true);

    
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables
}
